language: go

go:
  - 1.9.x
  - master

go_import_path: github.com/berryland/sugar
  
before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - $GOPATH/bin/dep ensure
  
script:
  - go test -v ./...
